[build]
  command = "npm run build"
  publish = "dist" # or your build folder
  functions = "netlify/functions" # if using serverless functions

[build.environment]
  NODE_VERSION = "18" # Match your local version